server:
  port: 80
spring:
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb+srv://jelpitconjuntos-app-dev:l5Ext8R5t0FVMh1u3fRV@conjuntos-dev-pri.ic6qr.mongodb.net/jelpitconjuntos-dev?retryWrites=true&w=majority&replicaSet=atlas-ortbcr-shard-0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: "userManagement"
  devtools:
    add-properties: false


management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: TRACE
  data:
    mongodb:
      core:
        MongoTemplate: INFO
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
    root: INFO


cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      use-default-aws-region-chain: true
      static: us-east-1
#Sqs
sqs:
  queue:
    logs: https://sqs.us-east-1.amazonaws.com/459762009635/jelpit-conjuntos-dev-queue-message-logs-dev
    userStandard: https://sqs.us-east-1.amazonaws.com/459762009635/jelpit-conjuntos-dev-sqs-userManagementStandardQueue

#Parameters Store
transversal:
  notifications:
    credentials: /dev/JelpitConjuntos/TransversalCredentials
#Resources
#DNS_LB: https://60el68f9g9.execute-api.us-east-1.amazonaws.com/dev/api
CORE_MANAGEMENT_NOTIFICATION: v1/coreManagement/notifications/
TRANSVERSAL_NOTIFICATIONS_URL: https://stg-notificaciones.solucionesbolivarsites.com
EMAIL_RESOURCE: api/mailings/send-email-template
PORTAL: preconjuntosjelpitcom

#Config users
TOKEN_EXPIRATION_TIME_EMAIL_MS : 691200000
TOKEN_EXPIRATION_TIME_SMS_MS : 300000
ACTIVATION_URL_ADMIN: https://dev-web.conjuntos.jelpit.com/activacion-usuario
TEMPLATE_ACTIVATION_ADMIN: activacion_admin

#S3
s3:
  bucket:
    nameChargeProperties: data-back-jelpit-conjuntos-dev
    nameFolder: uploadFiles
