server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database-cls-paramters-local.ca6h8s3xeq3e.us-east-1.rds.amazonaws.com:5432/logistica?currentSchema=logistica
    username: postgres
    password: administradorcls
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: logistica
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: "userManagement"


